services:
  - type: web
    name: cacao-api
    runtime: python
    envVars:
      PYTHON_VERSION: 3.10
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000