services:
  - type: web
    name: consumidor-api-cacao
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        # CAMBIAR DE 3.11 A 3.12
        value: 3.12.0 # O 3.12.x